import './globals.scss'
import 'bootstrap/dist/css/bootstrap.css'
import Header from "./components/layout/header/Header";
import Footer from "./components/layout/footer/Footer";
import Credits from "./components/layout/footer/Credits";
import { Inter } from 'next/font/google'
import Script from 'next/script'; // Import next/script
const inter = Inter({ subsets: ['latin'] })
import 'keen-slider/keen-slider.min.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
       <Script
        strategy="lazyOnload"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
      />
      <body className={inter.className}>
      <Header />
        {children}
        <Footer />
        <Credits />
        </body>
    </html>
  )
}
